# kingdoms config
kingdoms:
  kingdom_1:
    name: "Melromarc"
    color: "GREEN"
    cristal-location: "world, 13, 70, 13, 0, 0" # x, y, z, yaw, pitch, il faut respecter ce pattern sinon niveau code ça va bug
    cristal-cuboid: "world, 10, 0, 10, 20, 256, 20" # xMin, yMin, zMin, xMax, yMax, zMax, il faut respecter ce pattern sinon niveau code ça va bug
    safe-zone-cuboid: "world, 496, 0, 496, 751, 256, 751"
    total-territory-cuboid: "world, 1, 0, 1, 10000, 256, 10000"
    spawn-location: "world, 5, 70, 5, 0, 0"
    spawn-cuboid: "world, 496, 0, 496, 751, 256, 751"
  kingdom_2:
    name: "Elkia"
    color: "LIGHT_PURPLE"
    cristal-location: "world, -13, 70, 13"
    cristal-cuboid: "world, -10, 0, 10, -20, 256, 20"
    safe-zone-cuboid: "world, -496, 0, 496, -751, 256, 751"
    total-territory-cuboid: "world, -1, 0, 1, -9999, 256, 10000"
    spawn-location: "world, -5, 70, 5, 0, 0"
    spawn-cuboid: "world, -496, 0, 496, -751, 256, 751"
  kingdom_3:
    name: "Orario"
    color: "AQUA"
    cristal-location: "world, 13, 70, -13"
    cristal-cuboid: "world, 10, 0, -10, 20, 256, -20"
    safe-zone-cuboid: "world, 496, 0, -496, 751, 256, -751"
    total-territory-cuboid: "world, 1, 0, -1, 10000, 256, -9999"
    spawn-location: "world, 5, 70, -5, 0, 0"
    spawn-cuboid: "world, 496, 0, -496, 751, 256, -751"
  kingdom_4:
    name: "Lugnica"
    color: "YELLOW"
    cristal-location: "world, -13, 70, -13"
    cristal-cuboid: "world, -10, 0, -10, -20, 256, -20"
    safe-zone-cuboid: "world, -496, 0, -496, -751, 256, -751"
    total-territory-cuboid: "world, -1, 0, -1, -9999, 265, -9999"
    spawn-location: "world, -5, 70, -5, 0, 0"
    spawn-cuboid: "world, -496, 0, -496, -751, 256, -751"

# si t'as des questions sur ça hésite pas
game:
  world-name: "world"
  launch-date: "12/03/2022 10h55"
  base-crystal-health: 1000 # hp
  crystal-level-up-health-gain: 20
  resources-cristal-gain:
    diamond: 5
    emerald: 6
    gold-ingot: 2.5
    iron-ingot: 1
    coal: 0.02
    redstone: 0.02
    lapis-lazulli: 0.025
    life-gem: 5 # c'est en niveaux
  crystal-regen-after-death-time: 1728000 # = 48h
  crystal-regen-health: 2 # c'est en hp, pas en coeurs
  crystal-regen-time: 45 # c'est en secondes
  kingdom-chat-format: "%{guild_rank_prefix}% %{guild}% %{player_grade}% %{kingdom_color}%%{name}% &7:&f %{message}%"
  global-chat-format: "%{relation_color}%%{guild_rank_prefix}%%{guild}% %{player_grade}% %{kingdom_color}%%{name}% &7: %{kingdom_color}%%{message}%"
  global-chat-prefix: "@"
  golem-damage: 20 # c'est en hp
  golem-name: "Golème"
  cps-max-speed: 12
  max-cristal-level: 150
  kingdom-max-players: 50
  time-to-teleport-to-guild-home: 5 # c'est en secondes
  spawn-location: "world, 15000, 70, 15000, 0, 0" # c'est le spawn pour les joueurs qui n'ont pas de royaume. Lorsqu'il feront /spawn ça va les tp là