name: YvernalKingdom
main: fr.yvernal.yvernalkingdom.Main
version: 0.0.1
authors: [ Twah2em, Nishibaka ]
depend: [ GroupManager, HolographicDisplays, BossBar ]
commands:
  guild:
    aliases:
      - guilde
      - f
      - g
    description: Commande relative aux guildes.
  spawn:
    description: Se tp au spawn de son royaume